### ISSUE TITLE
Rename proposal: deployix

### ISSUE THREAD

**Issue by shlevy** [zalora/deployix#41]
While defnix does contain some novel improvements that might apply more generally (e.g. the customization mechanism), the primary driver has always been and will likely continue to be improving how nix can be used in the context of automated deployment. The project name should reflect that.

In particular I'm about to take a dependency on defnix in a non-Zalora project, so now is a good time to settle on a final name.
- [x] Rename repository
- [x] Update identifiers referring to defnix
- [x] Update documentation referring to defnix
- [ ] Rename defnixos (maybe something to do with services or functionalities)

**Comment by shlevy** [comment]
I'm happy to do the last several steps, but I can't do the first :smile:

@jekor

**Comment by shlevy** [comment]
Something involving "devops" or "scale" or something in that vein might do well too.

**Comment by fmap** [comment]
Still want (1)?

**Comment by shlevy** [comment]
If people like the new name, yeah.

**Comment by fmap** [comment]
It is the best name! There you go.

**Comment by shlevy** [comment]
Thanks! Will start working on the rest of this.

**Comment by shlevy** [comment]
Still need to figure out a name for defnixos. Any ideas?
